apiVersion: v1
kind: Service
metadata:
  name: miniprogram-api
  namespace: default
spec:
  replicas: 1
  selector:
    app: miniprogram-api
  template:
    metadata:
      labels:
        app: miniprogram-api
    spec:
      containers:
      - name: miniprogram-api
        image: miniprogram-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m" 